# Project information
site_name: Super Gluu Docs
site_description: Documentation for the Super Gluu Mobile Application

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: sources
repo_name: GluuFederation/docs-supergluu-prod
repo_url: https://github.com/GluuFederation/docs-supergluu-prod/
edit_uri: edit/3.0.0/3.0.0/sources

# Configuration
theme: 
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '3.0.0'
    
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite     
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '3.0.0': 'https://gluu.org/docs/supergluu/3.0.0/'
    - '3.1.3': 'https://gluu.org/docs/supergluu/3.1.3/'
- ' ': 'https:/gluu.org/docs'
- ' ': 'https:/gluu.org/docs'
pages:
- Home: 'index.md'
- User Guide: 'user-guide/index.md'
- Administration Guide: 'admin-guide/index.md'
- Developer Guide: 'developer-guide/index.md'
